# 建议使用application.yml配置文件，而不是application.properties配置文件。原因：前者树状结构一目了然，解决了中文编码问题
spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: wqz
    password: wqz
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wqz.example.springboot.model
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true

#mapper:
#  mappers: com.wqz.example.springboot.utils.mapper.BaseSinglePkTableMapper
#  identity: oracle
#  before: true
#  not-empty: false

server:
  servlet:
    context-path: /sb

# 自定义属性。注：自定义属性建议使用@ConfigurationProperties注解，而不是@Value
app-config:
  id: myid
  name: springboot练习
  desc: springboot官方文档部分信息解读

# nats配置
nats:
  enable: false
  host: localhost
  port: 4222

# 日志
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
    com:
      wqz:
        example:
          springboot: debug